codecov: true
coveralls: true
language: julia
julia:
  - nightly
  - 1.0.6
  - 1.3.1
  - 1.5.2

jobs:
  include:
    - stage: "Documentation"
      julia: 1.3.1
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip